import os

RECOGNIZER_TRAINING_SET_DIR = os.environ.get('RECOGNIZER_TRAINING_SET_DIR')
RECOGNIZER_TRAINING_NAMES = os.environ.get('RECOGNIZER_TRAINING_NAMES', '').split(',')
RECOGNIZER_URL = os.environ.get('RECOGNIZER_URL')
